name: '[Build] Console'

on:
  workflow_call:

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build-console:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: './global.json'
          cache: true
          cache-dependency-path: './src/Client/ActivityPaint.Client.Console/packages.lock.json'

      - name: Restore NuGets
        run: dotnet restore ./src/Client/ActivityPaint.Client.Console/ActivityPaint.Client.Console.csproj --locked-mode

      - name: Build
        run: dotnet build ./src/Client/ActivityPaint.Client.Console/ActivityPaint.Client.Console.csproj --no-restore -c Release
