name: '[Build] All'

on:
  workflow_call:

jobs:
  build-console:
    name: Build Console
    uses: ./.github/workflows/build-console.yml

  build-web:
    name: Build Web
    uses: ./.github/workflows/build-web.yml

  build-mobile:
    name: Build Mobile
    uses: ./.github/workflows/build-mobile.yml
