name: Console

on:
  workflow_call:
    inputs:
      run-build:
        type: boolean
        default: true
      run-test:
        type: boolean
        default: true

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  DOTNET_VERSION: '8.0.303'

jobs:
  build:
    runs-on: windows-latest
    if: ${{ inputs.run-build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore NuGets
        run: dotnet restore ./src/Client/ActivityPaint.Client.Console/ActivityPaint.Client.Console.csproj --locked-mode

      - name: Build
        run: dotnet build ./src/Client/ActivityPaint.Client.Console/ActivityPaint.Client.Console.csproj --no-restore -c Release

  test:
    needs: [build]
    runs-on: ubuntu-latest
    if: |
      always()
      && inputs.run-test
      && !contains(needs.build.result, 'failure')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Run Unit Tests
        uses: './.github/actions/run-unit-tests'
