name: Publish

on:
  push:
    branches:
      - master
      - release/**
  workflow_dispatch:
    inputs:
      run-build:
        type: boolean
        default: true
      run-test:
        type: boolean
        default: true
      run-publish:
        type: boolean
        default: false

jobs:
  build:
    if: ${{ inputs.run-build }}
    uses: ./.github/workflows/build-all.yml

  test-unit:
    needs: [build]
    if: ${{ !contains(needs.build.result, 'failure') && inputs.run-test != false }}
    uses: ./.github/workflows/test-unit.yml

  publish:
    needs: [build, test-unit]
    if: ${{ !contains(needs.build.result, 'failure') && !contains(needs.test-unit.result, 'failure') && (startsWith(github.ref, 'refs/heads/release/') || inputs.run-publish != false) }}
    uses: ./.github/workflows/publish-all.yml
