name: Publish

on:
  push:
    branches:
      - master
      - release/**
  workflow_dispatch:
    inputs:
      run-build:
        type: boolean
        default: true
      run-test:
        type: boolean
        default: true
      run-publish:
        type: boolean
        default: false

jobs:
  build:
    if: ${{ inputs.run-build == '' || inputs.run-build == true }}
    uses: ./.github/workflows/build-all.yml

  test-unit:
    needs: [build]
    if: |
      always()
      && !contains(needs.build.result, 'failure')
      && (inputs.run-test == '' || inputs.run-test == true)
    uses: ./.github/workflows/test-unit.yml

  publish:
    needs: [build, test-unit]
    if: |
      always()
      && !contains(needs.build.result, 'failure')
      && !contains(needs.test-unit.result, 'failure')
      && ((startsWith(github.ref, 'refs/heads/release/') && inputs.run-publish == '') || inputs.run-publish == true)
    uses: ./.github/workflows/publish-all.yml
