name: '[CI/CD] Release pipeline'

on:
  push:
    branches:
      - master
    tags:
      - v**
  workflow_dispatch:
    inputs:
      run-build:
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'
      run-test:
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'
      run-publish:
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'
      run-release:
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'

jobs:
  build:
    if: ${{ inputs.run-build != 'false' && !cancelled() }}
    uses: ./.github/workflows/build-all.yml

  test:
    needs: [build]
    if: |
      always()
      && !cancelled()
      && !contains(needs.build.result, 'failure')
      && inputs.run-test != 'false'
    uses: ./.github/workflows/test-all.yml

  publish:
    needs: [build, test]
    if: |
      always()
      && !cancelled()
      && !contains(needs.build.result, 'failure')
      && !contains(needs.test.result, 'failure')
      && ((startsWith(github.ref, 'refs/tags/v') && inputs.run-publish != 'false') || inputs.run-publish == 'true')
    uses: ./.github/workflows/publish-all.yml

  release:
    needs: [publish]
    if: |
      !cancelled()
      && !contains(needs.publish.result, 'failure')
      && inputs.run-release != 'false'
    uses: ./.github/workflows/release-all.yml
