name: '[Test] E2E Tests'

on:
  workflow_call:

jobs:
  run-e2e-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: './global.json'
          cache: true
          cache-dependency-path: './test/*.E2ETests/packages.lock.json'

      - name: Restore Test NuGets
        run: |
          dotnet restore ./test/ActivityPaint.Client.Web.E2ETests/ActivityPaint.Client.Web.E2ETests.csproj --locked-mode

      - name: Build E2E tests
        run: |
          dotnet build ./test/ActivityPaint.Client.Web.E2ETests/ActivityPaint.Client.Web.E2ETests.csproj --no-restore

      - name: Ensure browsers are installed
        run: pwsh ./test/ActivityPaint.Client.Web.E2ETests/bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Run Web E2E Tests
        run: dotnet test ./test/ActivityPaint.Client.Web.E2ETests/ActivityPaint.Client.Web.E2ETests.csproj --no-restore --no-build

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: my-artifact
          path: ./test/ActivityPaint.Client.Web.E2ETests/bin/Debug/net8.0/screenshots
