name: '[Test] All'

on:
  workflow_call:

jobs:
  run-unit-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/test-unit.yml

  run-integration-tests:
    name: Run Integration Tests
    needs: [run-unit-tests]
    uses: ./.github/workflows/test-integration.yml

  run-e2e-tests:
    name: Run E2E Tests
    needs: [run-unit-tests, run-integration-tests]
    uses: ./.github/workflows/test-e2e.yml
